### ISSUE TITLE
License please

### ISSUE THREAD

**Issue by heathermeeker** [GoEddie/DeploymentContributorFilterer#1]
Could you please apply a license (like BSD) to this code?

**Comment by GoEddie** [comment]
Sure, it is MIT it was on codeplex but didn't migrate across.

I'll add it at some point, if MIT doesn't work for you let me know :)

**Comment by heathermeeker** [comment]
Thank you very much!

**Comment by brtubb-patagonia** [comment]
Hi @GoEddie , do you mind adding the license when you get a chance? I can submit a PR if that's easier for you. Awesome project - works very well!

**Comment by GoEddie** [comment]
Hey yes please go ahead :)

**Comment by brtubb-patagonia** [comment]
@GoEddie - Thanks! I'll submit one shortly.
