### ISSUE TITLE
Required Contributor error with SQL Server 2017

### ISSUE THREAD

**Issue by palmerc7** [GoEddie/DeploymentContributorFilterer#11]
I came across this much-needed tool to publish only specific schemas between databases. I downloaded the latest build and copied the AgileSqlClub.SqlPackageFilter.dll to the folder: C:\Program Files (x86)\Microsoft SQL Server\140\DAC\bin.

During my publish I get this error:
*** An error occurred during deployment plan generation. Deployment cannot continue.
Error SQL0: Required contributor with id 'AgileSqlClub.SqlPackageFilter' could not be loaded.
Contributor initialization error.

My sqlpackage command does include these parameters:
/p:AdditionalDeploymentContributors=AgileSqlClub.DeploymentFilterContributor /p:AdditionalDeploymentContributorArguments="SqlPackageFilter=IgnoreSchema(DataSync)"

Am I missing something in the usage or is this a Bug?

**Comment by RoyC-Retail-Assist** [comment]
The project uses Microsoft.SqlServer.DacFx.x64 v15o.x.x.  Downgrading this to v140.x.x. allows it to work with SQL Server 2017 version of sqlpackage.exe

**Comment by palmerc7** [comment]
> If you downloaded the ZIP file from github and extracted it, you might need to right-click the dll and "unblock" it.

I did verify that the DLL was un-blocked.  Same result.  Just saw your new build as well.  Trying that.

**Comment by palmerc7** [comment]
Closing issue
