### ISSUE TITLE
Not working on latest version of sqlPackage.exe 18.4.1

### ISSUE THREAD

**Issue by nmummau** [GoEddie/DeploymentContributorFilterer#20]
I installed sqlPackage from the latest version: 18.4.1
I am following the directions in your readme, and I'm getting the following error:
`*** An error occurred during deployment plan generation. Deployment cannot continue.
Error SQL0: Required contributor with id 'AgileSqlClub.DeploymentFilterContributor' could not be loaded.
Contributor initialization error.`

I have sqlPackage.exe and AgileSqlClub.SqlPackageFilter.dll located here:
`C:\Program Files\Microsoft SQL Server\150\DAC\bin` 

I am using this: `/p:AdditionalDeploymentContributors=AgileSqlClub.DeploymentFilterContributor /p:AdditionalDeploymentContributorArguments="SqlPackageFilter=IgnoreSchema(blah)"`

Please let me know what other logs you would like.

**Comment by nmummau** [comment]
**Solution**
Download the source from this repo
Building the AgileSqlClub.SqlPackageFilter project locally
Use the resulting dll located at 
`\DeploymentContributorFilterer-master\SqlPackageFilter\bin\Debug\AgileSqlClub.SqlPackageFilter.dll` 

I'm not sure why this solves it, but I'm sure it's something about running the dll from an untrusted source.

**Comment by houdelou** [comment]
Thanks @nmummau , in fact, unblocking the dll worked for me.
![image](https://user-images.githubusercontent.com/1574313/83289565-3fcf7580-a1b3-11ea-99a4-e1c68000d123.png)
