### ISSUE TITLE
Master branch does not build - A local variable or function named 'match' is already defined 

### ISSUE THREAD

**Issue by bobgodfrey** [GoEddie/DeploymentContributorFilterer#25]
I am guessing a merge issue but downloaded the latest source and project does not build. 

Severity	Code	Description	Project	File	Line	Suppression State	Tool
Error	CS0128	A local variable or function named 'match' is already defined in this scope	AgileSqlClub.SqlPackageFilter	.. CommandLineFilterParser.cs	78	Active	Compiler

![image](https://user-images.githubusercontent.com/20686618/113038046-06192380-9164-11eb-9bc7-ce23e4153c8d.png)

**Comment by zyngh** [comment]
To build it, I changed "string match" to "string strMatch", then it built. I'm not a C# developer but it worked. Just in case someone needs the dll badly.

**Comment by t-johnson** [comment]
Seems to be as a result of a merge problem from commits:
ee77aee85384a8e813e15af6969bb0ffcefd1611
and
fec30ab03a8e26be98c9d1b4277d1c2f49b27811

**Comment by akshay52178** [comment]
@GoEddie the build issue is still there. Can you please merge the fix for this.
