### ISSUE TITLE
Support DacFx version 140?

### ISSUE THREAD

**Issue by t-johnson** [GoEddie/DeploymentContributorFilterer#3]
Hi Eddie,

any plan to update this to DacFx version 140?  i think it would require also targeting .net framework 4.6.1.

If i submit a pull request would you merge it?

thanks
tim

**Comment by GoEddie** [comment]
Hi Tim,

I would be happy to accept a pr :)

Ed

**Comment by t-johnson** [comment]
Super, doing it now.
