### ISSUE TITLE
Does this work with the sqlpackage.exe installed from `dotnet tools install -g microsoft.sqlpackage`

### ISSUE THREAD

**Issue by jdearing-neudesic** [GoEddie/DeploymentContributorFilterer#33]
I am 99% sure of the following two based on Sysinternals Process Monitor:

* I am using the sqlpackage.exe installed by `dotnet tools install -g microsoft.sqlpackage`
* The installation directory is `C:\Users\Justin.Dearing\.dotnet\tools`
* No attempt is being made to look for or load any file called `AgileSqlClub.DeploymentFilterContributor.*`
* This behavior occurs whether or not I unblock the DLL
* I tried the .net 4.8 and net standard 2,1binaries

Attempting to load your filter:

```cmd
PS C:\Users\Justin.Dearing\source\repos\whatever\sql\ExampleDatabase\bin\Output> sqlpackage /Action:Publish /p:AdditionalDeploymentContributors=AgileSqlClub.DeploymentFilterContributor /SourceFile:.\Whenever.dacpac /TargetConnectionString:"Server=(localdb)\MSSQLLocalDB;Initial Catalog=dummy"
Publishing to database 'dummy' on server '(localdb)\MSSQLLocalDB'.
Initializing deployment (Start)
Initializing deployment (Failed)
*** An error occurred during deployment plan generation. Deployment cannot continue.
Error SQL0: Required contributor with id 'AgileSqlClub.DeploymentFilterContributor' could not be loaded.

Contributor initialization error.
Time elapsed 0:00:08.77
```

Not loading your filter:

```cmd
PS C:\Users\Justin.Dearing\source\repos\whatever\sql\ExampleDatabase\bin\Output> sqlpackage /Action:Publish /SourceFile:.\Whenever.dacpac /TargetConnectionString:"Server=(localdb)\MSSQLLocalDB;Initial Catalog=dummy"
Publishing to database 'dummy' on server '(localdb)\MSSQLLocalDB'.
Initializing deployment (Start)
Initializing deployment (Complete)
Analyzing deployment plan (Start)
Analyzing deployment plan (Complete)
Updating database (Start)
Creating database dummy...
Creating SqlSchema [however]...
Creating SqlTable [however].[Messages]...
Creating SqlDefaultConstraint unnamed constraint on [however].[Messages]...
Creating SqlProcedure [however].[usp_the_thing]...
Update complete.
Updating database (Complete)
Successfully published database.
Changes to connection setting default values were incorporated in a recent release.  More information is available at https://aka.ms/dacfx-connection
Time elapsed 0:00:08.95
PS C:\Users\Justin.Dearing\source\repos\whatever\sql\ExampleDatabase\bin\Output>
```

**Comment by jdearing-neudesic** [comment]
Proof of files in the right place 

![image](https://user-images.githubusercontent.com/79166643/220425158-870969b5-4f58-4d55-bc2f-0f0d4a02b1ce.png)

**Comment by t-johnson** [comment]
Hi @jdearing-neudesic 

i'm not sure of the official recommendations of how to include plugins when sqlpackage is installed as a global tool, however...

on my machine when I install it as a global tool the actual sqlpackage.exe and all its dependencies is installed under: C:\Users\<me>\.dotnet\tools\.store\microsoft.sqlpackage\161.8089.0\microsoft.sqlpackage\161.8089.0\tools\net6.0\any\

I believe if you drop this plugin dll in this location, it _should_ work

Tim

**Comment by t-johnson** [comment]
@jdearing-neudesic 
It might be a little simpler than that - you can keep the AgileSqlClub.SqlPackageFilter.dll in a different folder,  and specify this path using the AdditionalDeploymentContributorPaths argument (see https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-publish?view=sql-server-ver16)

Tim
