### ISSUE TITLE
MSBUILD 17.5.1: Required contributor with id 'AgileSqlClub.DeploymentFilterContributor ' could not be loaded.

### ISSUE THREAD

**Issue by PetrPospisil** [GoEddie/DeploymentContributorFilterer#34]
Hi, 
we are using your contributor for deploying our databases. We recently came to the issue that the latest versions of MSBuild from Visual Studio 2022 are not able to successfully load the contributor.

It can be easily reproduced.

DLL itself is copied into
`C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\Extensions`

We have SSDT project with contributor specified 
`<DeploymentContributors>$(DeploymentContributors);AgileSqlClub.DeploymentFilterContributor</DeploymentContributors>`

When we run build in cmdline
`"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" "C:\path\file.sqlproj"`
in
Visual Studio v17.2.6 that uses MSBuild v17.2.1.25201 (my version, our old build agents) -> it works with no error.
but in
Visual Studio v17.5.3 that uses MSBuild v17.5.1.16304 (colleague version, our new build agents) -> it fails with
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\SSDT\Microsoft.Data.Tools
.Schema.SqlTasks.targets(525,5): Build error : Required contributor with id 'AgileSqlClub.DeploymentFilterContributor'
could not be loaded. [C:\path\file.sqlproj]
```
error.

Using "Process Monitor" tool I debugged that the DLL itself is loaded as image into "MSBuild" process without an error, but later it fails anyway so it is not a directory issue.
![image](https://user-images.githubusercontent.com/5891724/226899281-0fd9f0fd-8077-4652-afee-24e3726c4ba1.png)

We are using older version 1.4.4.1. (framework 4.7.2). It works in VS, but not in MSBuild. 
I also tried both your latest builds (framework 4.8.0, core) of DLLs and they does not work at all not even in VS.

The issue is not limited to one computer, it is the same in all computers with newer VS version. 
It is also not related to one version of VS, because the problem is probably there multiple latest versions already. We only noticed it now, because it seems that the build and deploy in the VS itself work. MS build command is used mainly in our pipeline build agents (we tried to update them now)...

Can you help me to find what the problem is? THX.

[Edit] Updated info about used versions.

**Comment by t-johnson** [comment]
Check which version of DacFX is being used.  The version of this extension used must be compatible.

**Comment by PetrPospisil** [comment]
Hi, thx for the help.

It seems that MSBuild loads "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\Microsoft.SqlServer.Dac.dll", but the Visual Studio itself does not.

Visual Studio v17.2.6 that uses MSBuild v17.2.1.25201 (my version, our old build agents) has 15.0.5472.2 version
Visual Studio v17.5.3 that uses MSBuild v17.5.1.16304 (colleague version, our new build agents) has 16.0.6389.0 version
Visual Studio itself has probably still the version 15. baked in so it is working with older version.

So, what should I do in order to support this new version of DacFX that MS build uses?

**Comment by PetrPospisil** [comment]
Hi, I tried to downgrade the referenced DacFx package and build new dlls

-		<PackageReference Include="Microsoft.SqlServer.DacFx" Version="161.6374.0" ExcludeAssets="runtime" />
+		<PackageReference Include="Microsoft.SqlServer.DacFx" Version="160.6296.0" ExcludeAssets="runtime" />

and it started to work.

Thx for pointing me the right direction.
