### ISSUE TITLE
Unit tests in project don't complete

### ISSUE THREAD

**Issue by AartBluestoke** [GoEddie/DeploymentContributorFilterer#35]
many of them fail with " StdErr: *** An error occurred during deployment plan generation. Deployment cannot continue.
Error SQL0: Required contributor with id 'AgileSqlClub.DeploymentFilterContributor' could not be loaded.

Contributor initialization error."

![image](https://github.com/GoEddie/DeploymentContributorFilterer/assets/1892829/458cdbea-1709-4a9b-bebe-e8ed092303e9)

**Comment by AartBluestoke** [comment]
logs:
Microsoft.Data.Tools.Diagnostics.Tracer Error: 0 : 2023-08-15T10:38:51 : SafeDirectoryCatalog: Extensibility failed to load DLL 'repos\DeploymentContributorFilterer\AgileSqlClub.SqlPackageFilter.IntegrationTests\bin\Debug\net4.8\SqlPackage.exe\AgileSqlClub.SqlPackageFilter.dll' due to an exception System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetEnumerator()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.SqlServer.Dac.Extensibility.DacExtensionHelper.TryLoadAssemblyCatalog(String file, ComposablePartCatalog& catalog)
    ThreadId=1
    DateTime=2023-08-15T00:38:51.2073788Z
Microsoft.Data.Tools.Diagnostics.Tracer Error: 0 : 2023-08-15T10:38:51 : SafeDirectoryCatalog: Extensibility failed to load DLL 'repos\DeploymentContributorFilterer\AgileSqlClub.SqlPackageFilter.IntegrationTests\bin\Debug\net4.8\SqlPackage.exe\Microsoft.Data.Tools.Schema.Tasks.Sql.dll' due to an exception System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetEnumerator()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.SqlServer.Dac.Extensibility.DacExtensionHelper.TryLoadAssemblyCatalog(String file, ComposablePartCatalog& catalog)
    ThreadId=1
    DateTime=2023-08-15T00:38:51.6528620Z
Microsoft.Data.Tools.Diagnostics.Tracer Error: 0 : 2023-08-15T10:38:51 : SafeDirectoryCatalog: Extensibility failed to load DLL 'repos\DeploymentContributorFilterer\AgileSqlClub.SqlPackageFilter.IntegrationTests\bin\Debug\net4.8\SqlPackage.exe\Microsoft.Data.Tools.Schema.Utilities.Sql.dll' due to an exception System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetEnumerator()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.SqlServer.Dac.Extensibility.DacExtensionHelper.TryLoadAssemblyCatalog(String file, ComposablePartCatalog& catalog)
    ThreadId=1
    DateTime=2023-08-15T00:38:51.6777494Z
Microsoft.Data.Tools.Diagnostics.Tracer Error: 19 : 2023-08-15T10:38:51 : Microsoft.SqlServer.Dac.DacServicesException: An error occurred during deployment plan generation. Deployment cannot continue.
Error SQL0: Required contributor with id 'AgileSqlClub.DeploymentFilterContributor' could not be loaded.
 ---> Microsoft.Data.Tools.Schema.Sql.Deployment.DeploymentFailedException: Contributor initialization error.
   at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeployment.InitializeContributors()
   at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeployment.InitializePlanGeneratator()
   at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeployment.CreateController(Action`1 msgHandler)
   at Microsoft.SqlServer.Dac.DacServices.CreateController(SqlDeployment deploymentEngine, ErrorManager errorManager)
   --- End of inner exception stack trace ---
    ThreadId=1
    DateTime=2023-08-15T00:38:51.9611984Z

**Comment by AartBluestoke** [comment]
@t-johnson 
I initially suspected so, but i had created the localdb, with the Testing database - that wouldn't allow some of the tests to work.

note the error - it is a reflection error during dll load


"'repos\DeploymentContributorFilterer\AgileSqlClub.SqlPackageFilter.IntegrationTests\bin\Debug\net4.8\SqlPackage.exe\Microsoft.Data.Tools.Schema.Utilities.Sql.dll' due to an exception System.Reflection.ReflectionTypeLoadException: "


2 of your tests pass anyway

(this is after i fixed the " /TargetServerName:localhost" on a couple of the tests over to localdb)

![image](https://github.com/GoEddie/DeploymentContributorFilterer/assets/1892829/b40355dd-4c9a-4243-b8d8-4f8ecb882389)

note: "can't talk to this db" gets a different error:
![image](https://github.com/GoEddie/DeploymentContributorFilterer/assets/1892829/0673e7aa-8a8d-4845-8a08-bb3353e2196c)
"     StdErr: *** Could not deploy package.
Unable to connect to target server 'localhost'. Please verify the connection information such as the server name, login credentials, and firewall rules for the target server.
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
The system cannot find the file specified"

**Comment by t-johnson** [comment]
@AartBluestoke what version of SqlPackage.exe are you using?

**Comment by AartBluestoke** [comment]
> @AartBluestoke what version of SqlPackage.exe are you using?

the one that came with the project in the AgileSqlClub.SqlPackageFilter.IntegrationTests\SqlPackage.exe folder

**Comment by AartBluestoke** [comment]
found the issue:
1. the version you ship in the integration tests folder is older, somewhere approximately a pre-release 18.1 package from 2019 - and so fails the unit tests unless updated to the latest:
![image](https://github.com/GoEddie/DeploymentContributorFilterer/assets/1892829/7cf2731f-1ada-48a3-b814-d75b72a37ce9)

sqlPackage versions from https://learn.microsoft.com/en-us/sql/tools/sqlpackage/release-notes-sqlpackage?view=sql-server-ver16#1740-sqlpackage
![image](https://github.com/GoEddie/DeploymentContributorFilterer/assets/1892829/28267f4c-b2a6-4c36-b4c7-e0303343ba90)

2.visual studio ships with a non-standard sql-package that is approximately v19.2 - and not library compatible with the official release (no 16.0.9anything versions of sqlPackage are listed) :(
![image](https://github.com/GoEddie/DeploymentContributorFilterer/assets/1892829/c0d49966-f125-4b96-93d7-303ba2f6c3f5)
3. when you get the latest filter library and the latest sqlpackage it works.
latest sqlPackage has a 161.x or 162.x version number. 
![image](https://github.com/GoEddie/DeploymentContributorFilterer/assets/1892829/6b601bc9-51fd-4140-bc4b-ea01fe2aa445)

running 
 dotnet tool install --local Microsoft.SqlPackage --version 162.0.52
as suggested at https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download or https://www.nuget.org/packages/Microsoft.SqlPackage/ helped.

**Comment by t-johnson** [comment]
Fixed in #36
