### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Iviglious** [GoEddie/DeploymentContributorFilterer#9]
Hi Eddie,
Very useful dll.
Thanks a lot. I use it actively.
It is possible to have a build/release for DAC 140?
The current dll seems to be build for DAC 120.
When I run it in DAC 140, it gives me the following error:
"Could not load file or assembly 'Microsoft.Data.Tools.Schema.Sql, Version=13.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'"

**Comment by dbut023** [comment]
Hi @Iviglious,

The source is already updated for DAC 140 but the binary link is still to codeplex so predates that change.

I can build the DLL without issue but the Integration tests aren't behaving for me. Am working on getting that going and will send a PR back with the updates.

**Comment by GoEddie** [comment]
Hey,

I have published a new release which should support 140 (and 150!)

Let me know if this works for you:

https://github.com/GoEddie/DeploymentContributorFilterer/releases/tag/1.4.4.1

Thanks,


ed

**Comment by Iviglious** [comment]
Thanks a lot! that’s great!
